# Generated by Django 5.2.17 on 2026-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(unique=True, verbose_name='ステージ番号 (1, 2, 3...)')),
                ('title', models.CharField(max_length=100, verbose_name='謎のタイトル')),
                ('statement', models.TextField(verbose_name='問題文（HTMLタグ可）')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mysteries/', verbose_name='謎の画像')),
                ('answer', models.CharField(max_length=100, verbose_name='正解')),
                ('hint_water', models.TextField(blank=True, null=True, verbose_name='水の魔法使い用ヒント')),
                ('hint_grass', models.TextField(blank=True, null=True, verbose_name='草の魔法使い用ヒント')),
                ('hint_fire', models.TextField(blank=True, null=True, verbose_name='炎の魔法使い用ヒント')),
                ('hint_ice', models.TextField(blank=True, null=True, verbose_name='氷の魔法使い用ヒント')),
                ('hint_time', models.TextField(blank=True, null=True, verbose_name='時間の魔法使い用ヒント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='チーム合言葉')),
                ('current_stage', models.IntegerField(default=1, verbose_name='現在のステージ番号')),
                ('time_remaining_seconds', models.IntegerField(default=1800, verbose_name='制限時間(秒)')),
                ('is_paused', models.BooleanField(default=False, verbose_name='タイマー停止中フラグ')),
                ('element', models.CharField(choices=[('none', '未決定'), ('water', '水の魔法使い'), ('grass', '草の魔法使い'), ('fire', '炎の魔法使い'), ('ice', '氷の魔法使い'), ('time', '時間の魔法使い')], default='none', max_length=20, verbose_name='選択された属性')),
                ('skill_time_used', models.BooleanField(default=False, verbose_name='時間魔法使用済み')),
                ('skill_ice_used', models.BooleanField(default=False, verbose_name='氷魔法使用済み')),
                ('last_event', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後のアクション')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
