# Generated by Django 5.2.17 on 2026-10-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escape_game', '0002_mystery_team_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystery',
            name='hint_fire',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='hint_grass',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='hint_ice',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='hint_time',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='hint_water',
        ),
    ]
