# Generated by Django 5.2.17 on 2026-10-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_game', '0003_remove_mystery_hint_fire_remove_mystery_hint_grass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='time_remaining_seconds',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='team',
            name='bonus_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='time_limit_seconds',
            field=models.IntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='element',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_event',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='skill_ice_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='skill_time_used',
            field=models.BooleanField(default=False),
        ),
    ]
