# Generated by Django 5.2.17 on 2026-10-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_game', '0004_remove_team_time_remaining_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='element',
            field=models.CharField(choices=[('none', '未設定'), ('time', '時間'), ('water', '水'), ('grass', '草'), ('fire', '炎'), ('ice', '氷')], default='none', max_length=20),
        ),
    ]
